# Generated by Django 2.1.2 on 2019-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0002_field_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.TextField(default='NoName'),
            preserve_default=False,
        ),
    ]
