# Generated by Django 2.1.2 on 2019-07-13 15:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automaton', '0003_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='mutator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='automaton.Mutator'),
            preserve_default=False,
        ),
    ]
