# Generated by Django 2.1.2 on 2019-07-13 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0004_auto_20190713_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutator',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
