# Generated by Django 2.1.2 on 2019-07-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0005_auto_20190713_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='mutator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='automaton.Mutator'),
        ),
    ]
