# Generated by Django 2.1.2 on 2019-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0006_auto_20190713_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='mutator',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='fields', to='automaton.Mutator'),
        ),
    ]
